import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product>[
      Product(
        category: Category.companionTree,
        id: 0,
        id_own: 0,
        name: "숲 속에 있는 듯, 소라고사리",
        price: 35000,
        description: "소라고사리의 잎은 붉으면서도 푸르러서 신비로워요.\n곁에서 새순을 내고 잘 자라면서 당신을 언제나 응원해줄 거에요.",
      ),
      Product(
        category: Category.companionTree,
        id: 1,
        id_own: 1,
        name: "당신에게 행운을 드릴게요, 청페페",
        price: 35000,
        description: "청페페는 빛나는 둥그런 잎들을 계속해서 만들어내며 행운을 불러올거에요.\n청페페를 통해 사랑하는 사람에게 행운을 선물하세요.",
      ),
      Product(
        category: Category.companionTree,
        id: 2,
        id_own: 2,
        name: "유해물질 흡수에 최강, 관음죽",
        price: 35000,
        description: "중국 관음산이 고향인 관음죽은 대나무를 축소 시켜 놓은 듯 쭉쭉 뻗은 모습이 인상적이에요.\n관음죽이 유해물질을 흡수하며 당신을 지켜줄거에요!",
      ),
      Product(
        category: Category.companionTree,
        id: 3,
        id_own: 3,
        name: "천연 가습기, 아디안텀",
        price: 35000,
        description: "아디안텀은 작고 부드러운 잎들이 흐드러진 모습이 마치 길가에 핀 야생화 같이 사랑스러운 친구예요.\n습기를 머금었다 건조할 때 뿜어내며 천연 가습기도 되어주니 반할 수 밖에요!",
      ),
      Product(
        category: Category.companionTree,
        id: 4,
        id_own: 4,
        name: "늘 푸른 잎사귀를 가진, 청아이비",
        price: 36000,
        description: "청아이비는 진실한 애정을 뜻해요.\n춤을 추듯 뻗어나가는 초록빛 잎들이 유쾌한 공간을 만들어줄거에요.",
      ),
      Product(
        category: Category.companionTree,
        id: 5,
        id_own: 5,
        name: "천 년을 사는 나무, 주목",
        price: 35000,
        description: "살아서 천 년, 죽어서도 썩지 않고 천 년을 산다는 주목은 장수와 영생을 상징해요.\n주목은 가볍고 잘 휘어지지 않으며, 붉은빛이 무병장수를 돕는다고 해서 예로부터 어르신께 주목 지팡이를 선물했다고 해요.",
      ),
      Product(
        category: Category.companionTree,
        id: 6,
        id_own: 6,
        name: "[가정의 달] 숲 만드는 카네이션 + 메세지카드 set",
        price: 38000,
        description: "소중한 마음을 전하는 어버이날, 그리고 스승의날에 사랑과 존경을 담은 카네이션을 선물하세요",
      ),
      Product(
        category: Category.companionTree,
        id: 7,
        id_own: 7,
        name: "강원 산불피해 복구 캠페인, B-GREEN AGAIN",
        price: 35000,
        description: "강원 산불피해 복구숲 만드는 황금사철",
      ),
      Product(
        category: Category.companionTree,
        id: 8,
        id_own: 8,
        name: "올리브나무, 비둘기가 물고 온 평화의 나무",
        price: 38000,
        description: "평화와 풍요를 담은 지중해의 나무",
      ),
      Product(
        category: Category.companionTree,
        id: 9,
        id_own: 9,
        name: "커피농가의 자립을 돕는, 커피나무",
        price: 35000,
        description: "기후변화로 사라져가는 르완다, 인도네시아, 에티오피아, 네팔 커피농가 재건을 위한 아라비카 커피나무",
      ),
      Product(
        category: Category.companionTree,
        id: 10,
        id_own: 10,
        name: "율마, 상큼한 레몬향 담긴 나무",
        price: 35000,
        description: "피톤치드 뿜뿜! 상큼한 레몬향 듬뿍 담은 율마",
      ),
      Product(
        category: Category.companionTree,
        id: 11,
        id_own: 11,
        name: "테이블야자, 책상 위의 작은 정글",
        price: 35000,
        description: "새집증후군 잡는 책상 위 공기청정기",
      ),
      Product(
        category: Category.companionTree,
        id: 12,
        id_own: 12,
        name: "홍콩야자, 우산을 닮은 나무",
        price: 35000,
        description: "하늘을 향해 뻗은 잎이 오손도손 매력적인 공기정화 나무입니다.",
      ),
      Product(
        category: Category.companionTree,
        id: 13,
        id_own: 13,
        name: "스파티필럼, 백조를 닮은 우아한 나무",
        price: 35000,
        description: "흰 꽃이 백조를 닮은 우아한 관엽식물",
      ),
      Product(
        category: Category.companionTree,
        id: 14,
        id_own: 14,
        name: "몬스테라, 하트를 닮은 나무",
        price: 38000,
        description: "하트를 닮은 나무, 몬스테라",
      ),
      Product(
        category: Category.companionTree,
        id: 15,
        id_own: 15,
        name: "새로운 시작을 응원해요. 수험생&신혼부부 응원 반려나무 무료지원",
        price: 0,
        description: "반려나무를 통해 수험생과 신혼부부를 응원합니다!\n* 나무 수종과, 화분은 랜덤으로 발송됩니다.\n* 대리신청하실 경우, 받으시는 분에게 배송 예정임을 미리 안내 부탁드립니다.",
      ),
      Product(
        category: Category.companionTree,
        id: 16,
        id_own: 16,
        name: "파랑새의 깃털을 닮은, 블루버드",
        price: 35000,
        description: "사시사철 달려있는 파아란 잎이 파랑새의 깃털을 닮은 블루버드",
      ),
      Product(
        category: Category.companionTree,
        id: 17,
        id_own: 17,
        name: "은은한 달빛 담은, 문그로우",
        price: 37000,
        description: "은은한 달빛을 닮아 문그로우라고 불리우는 매력적인 침엽수",
      ),
      Product(
        category: Category.companionTree,
        id: 18,
        id_own: 18,
        name: "사계절 풍경이 담긴, 남천",
        price: 35000,
        description: "사계절 풍경이 고스란히 담긴 남천은, 정원과 마당을 든든하게 지키는 나무로 사랑받아 왔어요.",
      ),
      Product(
        category: Category.companionTree,
        id: 19,
        id_own: 19,
        name: "한반도 멸종위기종, 울릉도 만병초",
        price: 36000,
        description: "울릉도에서 온 한반도 멸종위기종, 만병초",
      ),
      Product(
        category: Category.companionTree,
        id: 20,
        id_own: 20,
        name: "치자나무, 순백의 우아한 향기",
        price: 36000,
        description: "답답한 실내생활에 기분전환이 필요한 당신에게,\n새하얀 꽃잎, 우아한 향기를 가진 치자나무를 추천드려요.",
      ),
      Product(
        category: Category.companionTree,
        id: 21,
        id_own: 21,
        name: "오르비폴리아, 일렁이는 연녹빛 물결",
        price: 40000,
        description: "인테리어와 공기정화 둘 다 챙기고 싶은 당신에게,\n일렁이는 연녹빛 물결을 닮은 오르비폴리아를 추천드려요.",
      ),
      Product(
        category: Category.largeCompanionTree,
        id: 22,
        id_own: 0,
        name: "크리스마스 트리를 닮은, 아라우카리아",
        price: 120000,
        description: "겨울에도 파릇한 모습을 보여주는 매력적인 침엽수",
      ),
      Product(
        category: Category.largeCompanionTree,
        id: 23,
        id_own: 1,
        name: "아레카 야자, NASA 선정 공기정화식물 1위",
        price: 120000,
        description: "지구에서 가장 공기정화를 잘 하는 나무",
      ),
      Product(
        category: Category.largeCompanionTree,
        id: 24,
        id_own: 2,
        name: "스파티필럼, NASA 선정 공기정화식물 10위!",
        price: 120000,
        description: "흰 꽃이 백조를 닮은 우아한 관엽식물",
      ),
      Product(
        category: Category.largeCompanionTree,
        id: 25,
        id_own: 3,
        name: "눈보라 속에서 피어나는, 동백나무",
        price: 120000,
        description: "눈보라 속에서 피어나는 강인한 생명력의 동백나무입니다.",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 26,
        id_own: 0,
        name: "해충 싹쓸이 반려나무 관리제",
        price: 8000,
        description: "인체와 식물에 안전한 천연 해충 관리제예요.\n다양한 해충에 효과적으로 작용하며, 빠르게 해충과 작별할 수 있게 도와줘요!",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 27,
        id_own: 1,
        name: "우산 LED 식물등",
        price: 16000,
        description: "모든 식물에 사용 가능한 우산LED식물등",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 28,
        id_own: 2,
        name: "Dr.Joe 벅스킬 반려나무 해충 기피제",
        price: 8000,
        description: "천연 100% 유칼립투스, 벌레기피 성분 포함",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 29,
        id_own: 3,
        name: "Dr.Joe 뉴트리버블 반려나무 영양제",
        price: 5000,
        description: "반려나무 영양제 입니다.",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 30,
        id_own: 4,
        name: "상토 1L",
        price: 1500,
        description: "상토 1L 입니다.",
      ),
      Product(
        category: Category.potGardeningSupplies,
        id: 31,
        id_own: 5,
        name: "1달에 1번 물 주는 화분, 스밈 eco",
        price: 21000,
        description: "식물 키우기 두려웠던 분들을 위해서 태어났어요.\n1달에 1번 물주는 화분 스밈이 당신의 일상을 초록으로 채워줄 거예요!",
      ),
    ];
    if (category == Category.all) {
      return allProducts;
    } else {
      return allProducts.where((Product p) {
        return p.category == category;
      }).toList();
    }
  }
}